# Generated by Django 5.1.3 on 2024-11-21 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_author_book_bookshelf_shelves'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='icon',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='shelves',
            name='added',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shelves',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bookshelf.book'),
        ),
        migrations.AlterField(
            model_name='shelves',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bookshelf.bookshelf'),
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('profile1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile1', to='bookshelf.profile')),
                ('profile2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile2', to='bookshelf.profile')),
            ],
        ),
    ]
