# Generated by Django 5.1.3 on 2024-11-24 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_book_cover_bookshelf_created_bookshelf_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(blank=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('bookhelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.bookshelf')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('star', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.book')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.profile')),
            ],
        ),
    ]
