# Generated by Django 5.1.3 on 2024-11-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0004_alter_book_isbn_comment_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='published',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
