# Generated by Django 5.1.2 on 2024-11-10 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='precint',
            new_name='precinct',
        ),
    ]
