# Generated by Django 5.1.2 on 2024-11-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_rename_precint_voter_precinct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='precinct',
            field=models.CharField(max_length=2),
        ),
    ]
