# Generated by Django 5.1.2 on 2024-11-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0007_alter_voter_v21primary_alter_voter_v21town_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='v20state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v21primary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v21town',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v22general',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v23town',
            field=models.TextField(blank=True, null=True),
        ),
    ]
