# Generated by Django 5.1.3 on 2024-11-19 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_examples', '0004_remove_course_students_remove_student_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='grade',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='father_person', to='db_examples.person')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mother_person', to='db_examples.person')),
            ],
        ),
    ]
